const flavorCheckboxes = [

    //Flavors
    {
        id: 1,
        name: 'Sweet',
        key: 'checkBox1',
        label: 'Check Box 1',
    },
    {
        id: 2,
        name: 'Tropical',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        id: 3,
        name: 'Peach',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        id: 4,
        name: 'Minty',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        id: 5,
        name: 'Fruit',
        key: 'checkBox5',
        label: 'Check Box 5',
    },
    {
        id: 6,
        name: 'Coffee',
        key: 'checkBox6',
        label: 'Check Box 6',
    },
    {
        id: 7,
        name: 'Chemical',
        key: 'checkBox7',
        label: 'Check Box 7',
    },
    {
        id: 8,
        name: 'Blueberry',
        key: 'checkBox8',
        label: 'Check Box 8',
    },
    {
        id: 9,
        name: 'Pear',
        key: 'checkBox9',
        label: 'Check Box 9',
    },
    {
        id: 10,
        name: 'Apple',
        key: 'checkBox10',
        label: 'Check Box 10',
    },
    {
        id: 11,
        name: 'Woody',
        key: 'checkBox11',
        label: 'Check Box 11',
    },
    {
        id: 12,
        name: 'Cheese',
        key: 'checkBox12',
        label: 'Check Box 12',
    },
    {
        id: 13,
        name: 'Pungent',
        key: 'checkBox13',
        label: 'Check Box 13',
    },
    {
        id: 14,
        name: 'Flowery',
        key: 'checkBox14',
        label: 'Check Box 14',
    },
    {
        id: 15,
        name: 'Pepper',
        key: 'checkBox15',
        label: 'Check Box 15',
    },
    {
        id: 16,
        name: 'Sage',
        key: 'checkBox16',
        label: 'Check Box 16',
    },
    {
        id: 17,
        name: 'Chestnut',
        key: 'checkBox17',
        label: 'Check Box 17',
    },
    {
        id: 18,
        name: 'Strawberry',
        key: 'checkBox18',
        label: 'Check Box 18',
    },
    {
        id: 19,
        name: 'Honey',
        key: 'checkBox19',
        label: 'Check Box 19',
    },
    {
        id: 20,
        name: 'Mint',
        key: 'checkBox20',
        label: 'Check Box 20',
    },
    {
        id: 21,
        name: 'Orange',
        key: 'checkBox21',
        label: 'Check Box 21',
    },
    {
        id: 22,
        name: 'Tobacco',
        key: 'checkBox22',
        label: 'Check Box 22',
    },
    {
        id: 23,
        name: 'Tea',
        key: 'checkBox23',
        label: 'Check Box 23',
    },
    {
        id: 24,
        name: 'Lime',
        key: 'checkBox24',
        label: 'Check Box 24',
    },
    {
        id: 25,
        name: 'Grapefruit',
        key: 'checkBox25',
        label: 'Check Box 25',
    },
    {
        id: 26,
        name: 'Lavender',
        key: 'checkBox26',
        label: 'Check Box 26',
    },
    {
        id: 27,
        name: 'Tar',
        key: 'checkBox27',
        label: 'Check Box 27',
    },
    {
        id: 28,
        name: 'Skunk',
        key: 'checkBox28',
        label: 'Check Box 28',
    },
    {
        id: 29,
        name: 'Pine',
        key: 'checkBox29',
        label: 'Check Box 29',
    },
    {
        id: 30,
        name: 'Mango',
        key: 'checkBox30',
        label: 'Check Box 30',
    },
    {
        id: 31,
        name: 'Tree',
        key: 'checkBox31',
        label: 'Check Box 31',
    },
    {
        id: 32,
        name: 'Apricot',
        key: 'checkBox32',
        label: 'Check Box 32',
    },
    {
        id: 33,
        name: 'Vanilla',
        key: 'checkBox33',
        label: 'Check Box 33',
    },
    {
        id: 34,
        name: 'Berry',
        key: 'checkBox34',
        label: 'Check Box 34',
    },
    {
        id: 35,
        name: 'Menthol',
        key: 'checkBox35',
        label: 'Check Box 35',
    },
    {
        id: 36,
        name: 'Violet',
        key: 'checkBox36',
        label: 'Check Box 36',
    },
    {
        id: 37,
        name: 'Blue',
        key: 'checkBox37',
        label: 'Check Box 37',
    },
    {
        id: 38,
        name: 'Nutty',
        key: 'checkBox38',
        label: 'Check Box 38',
    },
    {
        id: 39,
        name: 'Grape',
        key: 'checkBox39',
        label: 'Check Box 39',
    },
    {
        id: 40,
        name: 'Pineapple',
        key: 'checkBox40',
        label: 'Check Box 40',
    },
    {
        id: 41,
        name: 'Diesel',
        key: 'checkBox41',
        label: 'Check Box 41',
        id: 1,
    },
    {
        id: 42,
        name: 'Ammonia',
        key: 'checkBox42',
        label: 'Check Box 42',
    },
    {
        id: 43,
        name: 'Plum',
        key: 'checkBox43',
        label: 'Check Box 43',
    },
    {
        id: 44,
        name: 'Lemon',
        key: 'checkBox44',
        label: 'Check Box 44',
    },
    {
        id: 45,
        name: 'Butter',
        key: 'checkBox45',
        label: 'Check Box 45',
    },
    {
        id: 46,
        name: 'Citrus',
        key: 'checkBox46',
        label: 'Check Box 46',
    },
    {
        id: 47,
        name: 'Rose',
        key: 'checkBox47',
        label: 'Check Box 47',
    },
    {
        id: 48,
        name: 'Earthy',
        key: 'checkBox48',
        label: 'Check Box 48',
    },
    {
        id: 49,
        name: 'Spicy/Herbal',
        key: 'checkBox49',
        label: 'Check Box 49',
    },
    {
        id: 50,
        name: 'None',
        key: 'checkBox50',
        label: 'Check Box 50',
    },
];

export default flavorCheckboxes;

// const flavor = [
//     { id: 1, name: "Sweet"},
//     { id: 2, name: 'Tropical'},
//     { id: 3, name: 'Peach'},
//     { id: 4, name: 'Minty'},
//     { id: 5, name: 'Fruit'},
//     { id: 6, name: 'Coffee'},
//     { id: 7, name: "Chemical"},
//     { id: 8, name: 'Blueberry'},
//     { id: 9, name: "Pear"},
//     { id: 10, name: "Apple"},
//     { id: 11, name: "Woody"},
//     { id: 12, name: "Cheese"},
//     { id: 13, name: "Pungent"},
//     { id: 14, name: "Flowery"},
//     { id: 15, name: "Pepper"},
//     { id: 16, name: "Sage"},
//     { id: 17, name: "Chestnut"},
//     { id: 18, name: "Strawberry"},
//     { id: 19, name: "Honey"},
//     { id: 20, name: "Mint"},
//     { id: 21, name: "Orange"},
//     { id: 22, name: "Tobacco"},
//     { id: 23, name: "Tea"},
//     { id: 24, name: "Lime"},
//     { id: 25, name: "Grapefruit"},
//     { id: 26, name: "Lavender"},
//     { id: 27, name: "Tar"},
//     { id: 28, name: "Skunk"},
//     { id: 29, name: "Pine"},
//     { id: 30, name: "Mango"},
//     { id: 31, name: "Tree"},
//     { id: 32, name: "Apricot"},
//     { id: 33, name: "Vanilla"},
//     { id: 34, name: "Berry"},
//     { id: 35, name: "Menthol"},
//     { id: 36, name: "Violet"},
//     { id: 37, name: "Blue"},
//     { id: 38, name: "Nutty"},
//     { id: 39, name: "Grape"},
//     { id: 40, name: "Pineapple"},
//     { id: 41, name: "Diesel"},
//     { id: 42, name: "Ammonia"},
//     { id: 43, name: "Plum"},
//     { id: 44, name: "Lemon"},
//     { id: 45, name: "Butter"},
//     { id: 46, name: "Citrus"},
//     { id: 47, name: "Rose"},
//     { id: 48, name: "Earthy"},
//     { id: 49, name: "Spicy/Herbal"},
//     { id: 50, name: "None"},

// ];