const flavorCheckboxes = [

    //Flavors
    {
        name: 'Sweet',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Tropical',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Peach',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Minty',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Fruit',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Coffee',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Chemical',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Blueberry',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Pear',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Apple',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Woody',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Cheese',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Pungent',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Flowery',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Pepper',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Sage',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Chestnut',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Strawberry',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Honey',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Mint',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Orange',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Tobacco',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Tea',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Lime',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Grapefruit',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Lavender',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Tar',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Skunk',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Pine',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Mango',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Tree',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Apricot',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Vanilla',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Berry',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Menthol',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Violet',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Blue',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Nutty',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Grape',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Pineapple',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Diesel',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Ammonia',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Plum',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Lemon',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Butter',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'Citrus',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
    {
        name: 'Rose',
        key: 'checkBox3',
        label: 'Check Box 3',
    },
    {
        name: 'Earthy',
        key: 'checkBox4',
        label: 'Check Box 4',
    },
    {
        name: 'Spicy/Herbal',
        key: 'checkBox1',
        label: 'Check Box 1',
        id: 1,
    },
    {
        name: 'None',
        key: 'checkBox2',
        label: 'Check Box 2',
    },
];

export default flavorCheckboxes;

// const flavor = [
//     { id: 1, name: "Sweet"},
//     { id: 2, name: 'Tropical'},
//     { id: 3, name: 'Peach'},
//     { id: 4, name: 'Minty'},
//     { id: 5, name: 'Fruit'},
//     { id: 6, name: 'Coffee'},
//     { id: 7, name: "Chemical"},
//     { id: 8, name: 'Blueberry'},
//     { id: 9, name: "Pear"},
//     { id: 10, name: "Apple"},
//     { id: 11, name: "Woody"},
//     { id: 12, name: "Cheese"},
//     { id: 13, name: "Pungent"},
//     { id: 14, name: "Flowery"},
//     { id: 15, name: "Pepper"},
//     { id: 16, name: "Sage"},
//     { id: 17, name: "Chestnut"},
//     { id: 18, name: "Strawberry"},
//     { id: 19, name: "Honey"},
//     { id: 20, name: "Mint"},
//     { id: 21, name: "Orange"},
//     { id: 22, name: "Tobacco"},
//     { id: 23, name: "Tea"},
//     { id: 24, name: "Lime"},
//     { id: 25, name: "Grapefruit"},
//     { id: 26, name: "Lavender"},
//     { id: 27, name: "Tar"},
//     { id: 28, name: "Skunk"},
//     { id: 29, name: "Pine"},
//     { id: 30, name: "Mango"},
//     { id: 31, name: "Tree"},
//     { id: 32, name: "Apricot"},
//     { id: 33, name: "Vanilla"},
//     { id: 34, name: "Berry"},
//     { id: 35, name: "Menthol"},
//     { id: 36, name: "Violet"},
//     { id: 37, name: "Blue"},
//     { id: 38, name: "Nutty"},
//     { id: 39, name: "Grape"},
//     { id: 40, name: "Pineapple"},
//     { id: 41, name: "Diesel"},
//     { id: 42, name: "Ammonia"},
//     { id: 43, name: "Plum"},
//     { id: 44, name: "Lemon"},
//     { id: 45, name: "Butter"},
//     { id: 46, name: "Citrus"},
//     { id: 47, name: "Rose"},
//     { id: 48, name: "Earthy"},
//     { id: 49, name: "Spicy/Herbal"},
//     { id: 50, name: "None"},

// ];